version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
  slack: circleci/slack@3.4.2
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
      - slack/status:
          fail_only: true
          mentions: 'yemiwebby'
          only_for_branches: master
          webhook: webhook
